version: '3.7'
services:
    db:
        image: postgres:12.2
        env_file: .env
    web:
        build: .
        volumes:
            - .:/sistem_portabil
        ports:
            - 8000:8000
        env_file: .env
        command: django-admin runserver 0.0.0.0:8000
        links:
            - db
        depends_on:
            - db
